name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache SwiftPM dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-
          
    - name: Build
      run: swift build --configuration release
      
    - name: Run tests
      run: swift test --configuration release
      
    - name: Build for iOS Simulator
      run: |
        xcodebuild -scheme "ARStudyGuide" \
          -sdk iphonesimulator \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          build